name: "Ubuntu"

on: [push, pull_request]

jobs:
  gcc-10:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-10]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Build Environment
      run: |
        sudo apt-get install -y libboost-coroutine-dev
        cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake --warn-uninitialized \
              -D CMAKE_BUILD_TYPE=${{matrix.build_type}} \
              $GITHUB_WORKSPACE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}
    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -j 10 -C ${{matrix.build_type}} --output-on-failure
